"use client";

import { useCallback, useEffect, useRef, useState } from "react";
import { Panel, ScoreBar } from "../components";

type RiskLevel = "HIGH" | "MEDIUM" | "LOW";

type Statement = {
  generatedAt: string;
  datasetCount: number;
  sceneCount: number;
  datasetGrades: {
    code: string;
    name: string;
    grade: string;
    status: string;
  }[];
  reviewStatusSummary: Record<string, number>;
  openReviewCount: number;
  riskDistribution: Record<RiskLevel, number>;
  riskCandidates: {
    label: string;
    count: number;
  }[];
  recentReviews: {
    reviewer: string;
    field: string;
    change: string;
    comment: string;
    time: string;
  }[];
  recentAuditEvents: {
    time: string;
    actor: string;
    action: string;
    target: string;
    detail: string;
  }[];
  averageSuitability: number;
  usageConditions: string[];
  recommendedUseScope: string[];
  itemsNeedingReview: {
    sceneId: string;
    status: string;
  }[];
};

type StatementResponse = {
  detail?: string;
  error?: string | null;
  partialSuccess?: boolean;
  statement?: Statement;
  success?: boolean;
};

type Message = {
  tone: "success" | "warning" | "error";
  text: string;
};

function formatNumber(value: number) {
  return new Intl.NumberFormat("ko-KR").format(value);
}

function riskTotal(riskDistribution: Record<RiskLevel, number>) {
  return riskDistribution.HIGH + riskDistribution.MEDIUM + riskDistribution.LOW;
}

function riskPercent(count: number, total: number) {
  if (total === 0) return 0;
  return Math.round((count / total) * 100);
}

function messageClassName(tone: Message["tone"]) {
  if (tone === "success") {
    return "border-emerald-300/25 bg-emerald-400/10 text-emerald-100";
  }

  if (tone === "warning") {
    return "border-amber-300/25 bg-amber-400/10 text-amber-100";
  }

  return "border-rose-300/25 bg-rose-400/10 text-rose-100";
}

export function SuitabilityStatementGenerator({
  autoGenerate,
}: {
  autoGenerate: boolean;
}) {
  const [isGenerating, setIsGenerating] = useState(false);
  const [message, setMessage] = useState<Message | null>(null);
  const [statement, setStatement] = useState<Statement | null>(null);
  const hasAutoGenerated = useRef(false);

  const generateStatement = useCallback(async function generateStatement() {
    setIsGenerating(true);
    setMessage(null);

    try {
      const response = await fetch("/api/reports/suitability-statement", {
        method: "POST",
      });
      const payload = (await response.json().catch(() => null)) as
        | StatementResponse
        | null;

      if (payload?.statement) {
        setStatement(payload.statement);
      }

      if (payload?.partialSuccess) {
        setMessage({
          tone: "warning",
          text:
            (payload.error ?? "Statement는 생성됐지만 audit log 기록 일부가 실패했습니다.") +
            (payload.detail ? " 상세: " + payload.detail : ""),
        });
        return;
      }

      if (!response.ok || payload?.success === false || !payload?.statement) {
        throw new Error(payload?.error ?? "Statement 생성에 실패했습니다.");
      }

      setMessage({
        tone: "success",
        text: "Data Suitability Statement 초안을 생성하고 audit log를 기록했습니다.",
      });
    } catch (error) {
      setMessage({
        tone: "error",
        text: error instanceof Error ? error.message : "Statement 생성에 실패했습니다.",
      });
    } finally {
      setIsGenerating(false);
    }
  }, []);

  useEffect(() => {
    if (!autoGenerate || hasAutoGenerated.current) return;
    hasAutoGenerated.current = true;
    void generateStatement();
  }, [autoGenerate, generateStatement]);

  const riskCount = statement ? riskTotal(statement.riskDistribution) : 0;

  return (
    <section id="suitability-statement" className="space-y-6">
      <Panel>
        <div className="flex flex-wrap items-start justify-between gap-4">
          <div>
            <h2 className="text-xl font-bold">Data Suitability Statement</h2>
            <p className="mt-2 max-w-3xl text-sm leading-6 text-slate-500">
              현재 Supabase 데이터를 기준으로 재사용 적합성 초안을 생성합니다. 이 초안은
              법률적 판정이 아니라 사용 전 검수 조건을 정리한 운영 참고 자료입니다.
            </p>
          </div>
          <button
            className="rounded-lg bg-violet-400 px-4 py-2 text-sm font-bold text-white hover:bg-violet-300 disabled:cursor-not-allowed disabled:opacity-55"
            disabled={isGenerating}
            onClick={() => void generateStatement()}
            type="button"
          >
            {isGenerating ? "생성 중..." : "Generate Statement"}
          </button>
        </div>

        {message ? (
          <p className={"mt-5 rounded-lg border p-3 text-sm font-semibold " + messageClassName(message.tone)}>
            {message.text}
          </p>
        ) : null}

        {!statement ? (
          <div className="mt-5 rounded-xl border border-white/10 bg-slate-950/45 p-5">
            <p className="text-sm leading-6 text-slate-500">
              아직 생성된 statement가 없습니다. 버튼을 누르면 Supabase live 데이터를 조회하고
              audit log에 생성 이벤트를 남깁니다.
            </p>
          </div>
        ) : (
          <div className="mt-5 space-y-5 rounded-xl border border-white/10 bg-slate-950/50 p-5">
            <div className="flex flex-wrap items-start justify-between gap-3">
              <div>
                <p className="text-sm font-bold text-sky-300">
                  Generated at {statement.generatedAt}
                </p>
                <h3 className="mt-2 text-2xl font-bold">
                  데이터 재사용 적합성 명세서 초안
                </h3>
                <p className="mt-3 max-w-4xl text-sm leading-7 text-slate-400">
                  총 {formatNumber(statement.datasetCount)}개 dataset,
                  {" "}{formatNumber(statement.sceneCount)}개 scene을 기준으로 생성했습니다.
                  평균 reuse suitability는 {statement.averageSuitability.toFixed(1)}점이며,
                  미확정 검수 항목은 {formatNumber(statement.openReviewCount)}건입니다.
                </p>
              </div>
              <span className="rounded-full bg-emerald-400/12 px-3 py-1 text-xs font-bold text-emerald-200 ring-1 ring-emerald-300/30">
                Live draft
              </span>
            </div>

            <div className="grid gap-3 md:grid-cols-4">
              <div className="rounded-lg bg-white/5 p-4">
                <p className="text-3xl font-bold text-sky-200">
                  {formatNumber(statement.datasetCount)}
                </p>
                <p className="mt-1 text-xs text-slate-500">Datasets</p>
              </div>
              <div className="rounded-lg bg-white/5 p-4">
                <p className="text-3xl font-bold text-violet-200">
                  {formatNumber(statement.sceneCount)}
                </p>
                <p className="mt-1 text-xs text-slate-500">Scenes</p>
              </div>
              <div className="rounded-lg bg-white/5 p-4">
                <p className="text-3xl font-bold text-amber-200">
                  {statement.averageSuitability.toFixed(1)}
                </p>
                <p className="mt-1 text-xs text-slate-500">Avg suitability</p>
              </div>
              <div className="rounded-lg bg-white/5 p-4">
                <p className="text-3xl font-bold text-rose-200">
                  {formatNumber(statement.openReviewCount)}
                </p>
                <p className="mt-1 text-xs text-slate-500">Needs review</p>
              </div>
            </div>

            <div className="grid gap-5 xl:grid-cols-2">
              <div className="rounded-lg border border-white/10 bg-white/5 p-4">
                <h4 className="font-bold">Review status summary</h4>
                <div className="mt-4 flex flex-wrap gap-2">
                  {Object.entries(statement.reviewStatusSummary).map(([status, count]) => (
                    <span
                      key={status}
                      className="rounded-full bg-white/8 px-3 py-1 text-xs font-bold text-slate-300 ring-1 ring-white/10"
                    >
                      {status}: {formatNumber(count)}
                    </span>
                  ))}
                </div>
              </div>

              <div className="rounded-lg border border-white/10 bg-white/5 p-4">
                <h4 className="font-bold">Dataset grades</h4>
                <div className="mt-4 space-y-2">
                  {statement.datasetGrades.map((dataset) => (
                    <div
                      key={dataset.code}
                      className="flex flex-wrap items-center justify-between gap-2 text-sm"
                    >
                      <span className="font-semibold text-slate-300">
                        {dataset.code} · {dataset.name}
                      </span>
                      <span className="font-bold text-amber-200">
                        {dataset.grade} · {dataset.status}
                      </span>
                    </div>
                  ))}
                </div>
              </div>
            </div>

            <div className="grid gap-5 xl:grid-cols-2">
              <div className="rounded-lg border border-white/10 bg-white/5 p-4">
                <h4 className="font-bold">Risk distribution</h4>
                <div className="mt-5 space-y-4">
                  <ScoreBar
                    label={"HIGH · " + formatNumber(statement.riskDistribution.HIGH) + "건"}
                    value={riskPercent(statement.riskDistribution.HIGH, riskCount)}
                    tone="rose"
                  />
                  <ScoreBar
                    label={"MEDIUM · " + formatNumber(statement.riskDistribution.MEDIUM) + "건"}
                    value={riskPercent(statement.riskDistribution.MEDIUM, riskCount)}
                    tone="gold"
                  />
                  <ScoreBar
                    label={"LOW · " + formatNumber(statement.riskDistribution.LOW) + "건"}
                    value={riskPercent(statement.riskDistribution.LOW, riskCount)}
                    tone="green"
                  />
                </div>
              </div>

              <div className="rounded-lg border border-white/10 bg-white/5 p-4">
                <h4 className="font-bold">Major risk candidates</h4>
                <div className="mt-4 flex flex-wrap gap-2">
                  {statement.riskCandidates.length > 0 ? (
                    statement.riskCandidates.map((candidate) => (
                      <span
                        key={candidate.label}
                        className="rounded-full bg-rose-400/12 px-3 py-1 text-xs font-bold text-rose-200 ring-1 ring-rose-300/25"
                      >
                        {candidate.label} · {candidate.count}
                      </span>
                    ))
                  ) : (
                    <p className="text-sm text-slate-500">표시할 risk candidate가 없습니다.</p>
                  )}
                </div>
              </div>
            </div>

            <div className="grid gap-5 xl:grid-cols-2">
              <div className="rounded-lg border border-white/10 bg-white/5 p-4">
                <h4 className="font-bold">권리·윤리·맥락상 사용주의 조건</h4>
                <ul className="mt-4 space-y-2 text-sm leading-6 text-slate-400">
                  {statement.usageConditions.map((condition) => (
                    <li key={condition}>- {condition}</li>
                  ))}
                </ul>
              </div>

              <div className="rounded-lg border border-white/10 bg-white/5 p-4">
                <h4 className="font-bold">추천 활용 가능 범위</h4>
                <ul className="mt-4 space-y-2 text-sm leading-6 text-slate-400">
                  {statement.recommendedUseScope.map((scope) => (
                    <li key={scope}>- {scope}</li>
                  ))}
                </ul>
              </div>
            </div>

            <div className="grid gap-5 xl:grid-cols-2">
              <div className="rounded-lg border border-white/10 bg-white/5 p-4">
                <h4 className="font-bold">미검수 또는 추가 검토 필요 항목</h4>
                <div className="mt-4 flex flex-wrap gap-2">
                  {statement.itemsNeedingReview.length > 0 ? (
                    statement.itemsNeedingReview.map((item) => (
                      <span
                        key={item.sceneId}
                        className="rounded-full bg-amber-400/12 px-3 py-1 text-xs font-bold text-amber-200 ring-1 ring-amber-300/25"
                      >
                        {item.sceneId} · {item.status}
                      </span>
                    ))
                  ) : (
                    <p className="text-sm text-slate-500">현재 미확정 검수 항목이 없습니다.</p>
                  )}
                </div>
                <h4 className="mt-6 font-bold">Recent review changes</h4>
                <div className="mt-4 space-y-3">
                  {statement.recentReviews.length > 0 ? (
                    statement.recentReviews.map((review) => (
                      <div key={review.time + review.field} className="text-sm">
                        <p className="font-bold text-slate-300">
                          {review.field} · {review.change}
                        </p>
                        <p className="mt-1 text-xs text-slate-500">
                          {review.time} · {review.reviewer}
                        </p>
                        <p className="mt-1 leading-5 text-slate-500">{review.comment}</p>
                      </div>
                    ))
                  ) : (
                    <p className="text-sm text-slate-500">최근 review 이력이 없습니다.</p>
                  )}
                </div>
              </div>

              <div className="rounded-lg border border-white/10 bg-white/5 p-4">
                <h4 className="font-bold">Recent audit events</h4>
                <div className="mt-4 space-y-3">
                  {statement.recentAuditEvents.map((event) => (
                    <div key={event.time + event.action} className="text-sm">
                      <p className="font-bold text-slate-300">
                        {event.action} · {event.target}
                      </p>
                      <p className="mt-1 text-xs text-slate-500">
                        {event.time} · {event.actor}
                      </p>
                      <p className="mt-1 leading-5 text-slate-500">{event.detail}</p>
                    </div>
                  ))}
                </div>
              </div>
            </div>
          </div>
        )}
      </Panel>
    </section>
  );
}
